apiVersion: kobeexperiment.kobe.com/v1alpha1
kind: KobeExperiment
metadata:
  name: kobeexp1
spec:
  benchmark: kobebenchmark1
  federator: kobefederator1
  runFlag: true
  clientImage: perl
  clientCommand: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
