apiVersion: kobefederator.kobe.com/v1alpha1
kind: KobeFederator
metadata:
  name: kobefederator1
spec:
  # Add fields here
  image: nginx
  imagePullPolicy: IfNotPresent
  port: 80
  initContainer:
  - name: container
    image: ubuntu
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'sleep 30']
