apiVersion: kobeexperiment.kobe.com/v1alpha1
kind: KobeExperiment
metadata:
  name: kobeexp1
spec:
  benchmark: kobebenchmark1
  federator: semagrow
  timesToRun: 2
  runFlag: false
  evalImage: perl
  evalCommands: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
