apiVersion: kobedataset.kobe.com/v1alpha1
kind: KobeDataset
metadata:
  name: dbpedia
spec:
  # Add fields here
  image: kostbabis/virtuoso
  toDownload: true
  downloadFrom: http://users.iit.demokritos.gr/~gmouchakis/dumps/DBPedia-Subset.tar.gz
  imagePullPolicy: Always
  count: 1
  group: kobe
  port: 8890

