apiVersion: kobefederator.kobe.com/v1alpha1
kind: KobeFederator
metadata:
  name: semagrow
spec:
  image: semagrow/semagrow
  imagePullPolicy: Always
  port: 8080
  confFromFileImage: kostbabis/semagrow-init
  inputFileDir: /sevod-scraper/input
  outputFileDir: /sevod-scraper/output
  confImage: kostbabis/semagrow-init-all
  fedConfDir: /etc/default/semagrow
  sparqlEnding: /SemaGrow/sparql

